# substitutions:
#   device_name: device_abc
#   friendly_name: Device ABC

<<: !include _common.yaml

esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

esp32_camera:
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]  # the order of the data_pins is significant, don't mix up the order
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  name: ${friendly_name}
  idle_framerate: 0.1fps

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    output: gpio_4
    name: ${friendly_name}
