esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    inverted: True
    number: GPIO13

sensor:
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 30s

switch:
  - platform: gpio
    pin: GPIO12
    name: ${friendly_name} Relay
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
