# substitutions:
#   device_name: device_abc
#   friendly_name: Device ABC

<<: !include _common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${friendly_name}
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    inverted: True
    number: GPIO13

switch:
  - platform: gpio
    pin: GPIO12
    name: ${friendly_name}
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
