esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

sensor:
  - platform: wifi_signal
    name: ${device_name}_wifi_signal
    update_interval: 30s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
