# substitutions:
#   device_name: device_abc
#   friendly_name: Device ABC

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  fast_connect: True

captive_portal:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 30s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID
    mac_address:
      name: ${friendly_name} Mac Address
  - platform: version
    name: ${friendly_name} ESPHome Version
