substitutions:
  device_name: wemos_rainbow_light
  friendly_name: Rainbow Light

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

<<: !include _common.yaml

output:
  # Register the blue LED as a dimmable output ....
  - platform: esp8266_pwm
    id: blue_led
    pin: D4
    inverted: True
light:
  - platform: neopixelbus
    pin: GPIO3 # RX
    num_leds: 16
    name: ${friendly_name}
    effects:
      - addressable_rainbow:
          name: Rainbow
          speed: 10
          width: 256
      - addressable_random_twinkle:
          name: Twinkle
          twinkle_probability: 5%
          progress_interval: 32ms
      - addressable_fireworks:
          name: Fireworks
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: true
          fade_out_rate: 120
      - addressable_scan:
          name: Scan
          move_interval: 100ms
