substitutions:
  device_name: d1mini_coffee_button_pusher
  friendly_name: Coffee Button Pusher

esphome:
  name: ${device_name}
  platform: ESP8266
  board: d1_mini

<<: !include _common.yaml

### https://esphome.io/components/servo.html

switch:
  - platform: template
    id: my_switch
    name: ${friendly_name}
    assumed_state: true
    restore_state: true
    optimistic: true
    turn_on_action:
    - servo.write:
        id: my_servo
        level: -0.35
    - delay: 0.4s
    - switch.turn_off: my_switch
    turn_off_action:
      - servo.write:
          id: my_servo
          level: 0

servo:
  - id: my_servo
    output: pwm_output

output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D1
    frequency: 50 Hz

# Home Assistant
# input_number:
#   servo_control:
#     name: Servo Control
#     initial: 0
#     min: -100
#     max: 100
#     step: 1
#     mode: slider

# automation:
#   - alias: Write Servo Value to ESP
#     trigger:
#       platform: state
#       entity_id: input_number.servo_control
#     action:
#       # Replace livingroom with the name you gave the ESP
#       - service: esphome.${device_name}
#         data_template:
#           level: '{{ trigger.to_state.state | int }}'
