substitutions:
  device_name: i3mega
  friendly_name: Anycubic i3 mega
  ip_address: 192.168.90.140

<<: !include _esp01s.yaml
<<: !include _common.yaml

switch:
  - platform: gpio
    name: "${friendly_name} Relay"
    pin: GPIO0
    id: relay
