# substitutions:
#   device_name: device_abc
#   friendly_name: Device ABC

<<: !include _common.yaml

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

binary_sensor:
  - platform: gpio
    internal: true
    id: _button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
