# substitutions:
#   device_name: device_abc
#   friendly_name: Device ABC

<<: !include _common.yaml
<<: !include _sonoff_s31lite.yaml

# Configuration for power monitor
uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    pin: GPIO12
    name: ${friendly_name} Relay
    id: relay
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  - platform: cse7766
    current:
      name: ${friendly_name} Current
    voltage:
      name: ${friendly_name} Voltage
    power:
      name: ${friendly_name} Wattage
